sudo: false
language: python
os: linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

# Python 3.7 needs a special treatment until it is supported by default
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial

addons:
   apt:
      packages:
         - libhdf5-serial-dev
         - netcdf-bin
         - libnetcdf-dev

install:
  - pip install tox-travis==0.11

script:
  - tox
